### ISSUE TITLE
can't add this package

### ISSUE THREAD

**Issue by JTL1992** [rcy/meteor-nouislider#11]
throw error;
            ^
Error: couldn't read entire resource
    at Object.files.readBufferWithLengthAndOffset (/tools/fs/files.js:1599:13)
    at /tools/isobuild/isopack.js:1001:26
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/nuonuo-jtl/.meteor/packages/meteor-tool/.1.3.4_1.e0ww2e++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/isopack.js:999:9
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/nuonuo-jtl/.meteor/packages/meteor-tool/.1.3.4_1.e0ww2e++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Isopack._loadUnibuildsFromPath (/tools/isobuild/isopack.js:965:7)
    at Isopack._.extend.initFromPath (/tools/isobuild/isopack.js:885:17)
    at /tools/isobuild/isopack-cache.js:286:23
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/isobuild/isopack-cache.js:272:24
    at Function.time (/tools/tool-env/profile.js:305:10)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:262:15)
    at /tools/isobuild/isopack-cache.js:76:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/Users/nuonuo-jtl/.meteor/packages/meteor-tool/.1.3.4_1.e0ww2e++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object].eachPackage (/tools/packaging/package-map.js:49:7)
    at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:75:24)
    at /tools/project-context.js:771:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._.extend._buildLocalPackages (/tools/project-context.js:770:18)
    at /tools/project-context.js:281:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:271:18)
    at /tools/project-context.js:263:12
    at Function.run (/tools/tool-env/profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:262:13)
    at /tools/cli/commands-packages.js:2041:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Command.main.registerCommand.name [as func] (/tools/cli/commands-packages.js:2040:27)
    at /tools/cli/main.js:1402:23

**Comment by JTL1992** [comment]
version  Meteor 1.3.4.1.

**Comment by dean0x** [comment]
I would love to see an implementation of this in the newer Version of meteor 1.3.4.1 as well.
Any kind of guidance on how to import it and use it inside a controller with the new constructor and class annotation would be highly appreciated

**Comment by FranciscoGutierrez** [comment]
There is no need to update this repository, use NPM modules instead.
`meteor npm install --save nouislider
`
Then in your file:
` import noUiSlider from 'noUiSlider';
`
```
Template.mytemplate.rendered = function () {
  var slider = document.getElementById('slider');
  noUiSlider.create(slider, {
    start: 0,
    connect: "lower",
    range: {
      'min': 0,
      'max': 100
    }
  });
};
```
